version: '3.2'

services:
  tattle-tale:
    build:
      context: ./
    environment:
      TT_SHADOW_USER:
      TT_SHADOW_PASS:
      TT_SNMP_COMMUNITY_STRING:
        # Change to match your naming convention
        # BTW, https://regex101.com is really good for testing regex
      TT_INT_DESCRIPTION_PEER_NAME_REGEX: "\[NAME=(.+?)\]"

  filebeat:
    build:
      context: filebeat/
    ports:
      # Replace 0.0.0.0 with the IP of the interface receiving netflow
      - "0.0.0.0:2055:2055/udp"
    depends_on:
      - logstash

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 8.0.0
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      # Replace 0.0.0.0 with the IP address you want the web interface to run on
      - "0.0.0.0:5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:

